### ISSUE TITLE
Crash upon Loading the latest Journal

### ISSUE THREAD

**Issue by GPoliceMZ** [AZaps/Elite-Dangerous-X52-MFD#13]
I had a crash while changing my Ship from a Imperial Courier to a ASP Explorer. I had to manually delete the Latest Journal File for the Application to work again.
[Journal.zip](https://github.com/AZaps/Elite-Dangerous-X52-MFD/files/1254227/Journal.zip)

**Comment by AZaps** [comment]
Hi GPoliceMZ,

It seems ED might have changed some of the ship names causing the crash. I was able to reproduce this on my end and edits have been made.

I have released a new version fixing this issue. Unfortunately, this may happen again in the future in case names are changed again. Please send in the journal file again as it was extremely helpful in resolving this issue.

I will leave this issue open for a week or until I receive a response.

Thanks!

**Comment by GPoliceMZ** [comment]
Hi AZaps,

Thanks for the Quick Response. I downloaded the latest Release and cannot reproduce the Error anymore. It works perfectly with my X-52 Pro, without any Issue anymore. Thank you for this.
