### ISSUE TITLE
Credits is limited to a 32-bit signed int

### ISSUE THREAD

**Issue by edusperoni** [AZaps/Elite-Dangerous-X52-MFD#14]
Although creditBalance is defined as `long long` in the `mfdPage0` struct, it's being cast as `long`:

https://github.com/AZaps/Elite-Dangerous-X52-MFD/blob/9b15187e2105230c5d603514b1b2997640452b33/EliteDangerousX52MFD/EliteDangerousX52MFD/JSONDataStructure.cpp#L282

Which means credits wrap around 2147483647 to -2147483647.

I believe casting it to long long should solve the problem (can't test it right now because I haven't set up  the SDK and build tools v141)

**Comment by AZaps** [comment]
Yes, good find. I will correct this in the next update this week.

I will also check for further mis-definitions like this but I believe this is the only numerical variable.

**Comment by AZaps** [comment]
The type mis-match has been fixed. Thanks for the report!
