### ISSUE TITLE
Crash, when Loading Game inside SRV

### ISSUE THREAD

**Issue by GPoliceMZ** [AZaps/Elite-Dangerous-X52-MFD#15]
Hello again,

I have noticed another Issue which crashes the Program. If you start the Game, while you are out driving a SRV, the App will immediately crash. I have added the Latest Journal File to this Issue. Thank you for your Support.
[Journal.zip](https://github.com/AZaps/Elite-Dangerous-X52-MFD/files/1626211/Journal.zip)

**Comment by AZaps** [comment]
No problem, I will take a look through the attached Journal (thanks for including this) and see what's causing the issue. I am looking to get this updated later this week.

**Comment by AZaps** [comment]
Was able to determine the root cause of the issue. There has been a new release published. Thanks for the report!
